name: push-image-develop

on:
  push:
    branches:
      - develop

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          echo "tag_name=$(echo $GITHUB_SHA | head -c 5)" >> $$GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: Dockerfile.production
          push: true
          tags: vitor96k/duck-proxy:latest,vitor96k/duck-proxy:${{ steps.vars.outputs.tag_name }} 
          platforms: linux/amd64,linux/arm64
